INSERT INTO destinations (
  destination_name,
  slug,
  state,
  country,
  short_description,
  full_description,
  published,
  featured,
  show_in_navigation,
  navigation_order,
  hero_heading,
  hero_subheading,
  hero_description,
  hero_image_url,
  hero_image_alt,
  hero_cta_text,
  why_visit_heading,
  why_visit_description,
  best_time_heading,
  best_time_summary,
  meta_title,
  meta_description,
  primary_keyword
)
VALUES
  (
    'New York',
    'new-york',
    'New York',
    'United States',
    'Iconic skyline, Broadway, and world-class museums.',
    'New York City blends culture, cuisine, and energy. Search flights, then call our desk to ticket your trip by phone.',
    TRUE,
    TRUE,
    TRUE,
    1,
    'New York',
    'The city that never sleeps',
    'Search live fares to NYC, then call a specialist to ticket by phone — 24/7 for Canada and the USA.',
    '/images/destinations/newYork.png',
    'New York City skyline',
    'Call to book',
    'Why visit New York?',
    'From Central Park to Times Square, New York delivers iconic sights and nonstop energy.',
    'Best time to visit',
    'Spring and fall offer milder weather and lively festivals. Summer is busy; winter brings holiday lights.',
    'Flights to New York | FlightBugs',
    'Book flights to New York by phone. Search live fares, then call FlightBugs 24/7.',
    'flights to New York'
  ),
  (
    'Orlando',
    'orlando',
    'Florida',
    'United States',
    'Theme parks, sunshine, and family getaways.',
    'Orlando is a top family destination. Search fares, then call our desk to ticket by phone.',
    TRUE,
    FALSE,
    TRUE,
    2,
    'Orlando',
    'Theme-park capital',
    'Search live fares to Orlando, then call a specialist to ticket by phone.',
    '/images/destinations/miami.png',
    'Orlando Florida travel destination',
    'Call to book',
    'Why visit Orlando?',
    'World-famous parks, warm weather, and easy family itineraries make Orlando a favorite escape.',
    'Best time to visit',
    'October–April brings milder temperatures and shorter park lines than peak summer.',
    'Flights to Orlando | FlightBugs',
    'Book flights to Orlando by phone. Search live fares, then call FlightBugs 24/7.',
    'flights to Orlando'
  ),
  (
    'Las Vegas',
    'las-vegas',
    'Nevada',
    'United States',
    'Shows, nightlife, and desert getaways.',
    'Las Vegas pairs entertainment with easy flight access. Search, then ticket by phone with our desk.',
    TRUE,
    TRUE,
    TRUE,
    3,
    'Las Vegas',
    'Lights on the Strip',
    'Search live fares to Las Vegas, then call a specialist to ticket by phone.',
    '/images/destinations/lasVegas.png',
    'Las Vegas Strip at night',
    'Call to book',
    'Why visit Las Vegas?',
    'Shows, dining, and desert day trips make Las Vegas a flexible weekend or week-long escape.',
    'Best time to visit',
    'March–May and September–November offer cooler evenings than midsummer heat.',
    'Flights to Las Vegas | FlightBugs',
    'Book flights to Las Vegas by phone. Search live fares, then call FlightBugs 24/7.',
    'flights to Las Vegas'
  ),
  (
    'Miami',
    'miami',
    'Florida',
    'United States',
    'Beaches, Art Deco, and vibrant nightlife.',
    'Miami mixes beach days with culture and cuisine. Search fares, then call to ticket by phone.',
    TRUE,
    TRUE,
    TRUE,
    4,
    'Miami',
    'Sun, sand, and skyline',
    'Search live fares to Miami, then call a specialist to ticket by phone.',
    '/images/destinations/miami.png',
    'Miami beach and skyline',
    'Call to book',
    'Why visit Miami?',
    'Beaches, neighborhoods, and a strong food scene make Miami a year-round draw.',
    'Best time to visit',
    'November–April is peak season with lower humidity; summer is hotter with occasional storms.',
    'Flights to Miami | FlightBugs',
    'Book flights to Miami by phone. Search live fares, then call FlightBugs 24/7.',
    'flights to Miami'
  ),
  (
    'Los Angeles',
    'los-angeles',
    'California',
    'United States',
    'Coastline, studios, and sprawling neighborhoods.',
    'Los Angeles spans beaches, hills, and entertainment. Search, then ticket by phone with our desk.',
    TRUE,
    FALSE,
    TRUE,
    5,
    'Los Angeles',
    'City of angels',
    'Search live fares to Los Angeles, then call a specialist to ticket by phone.',
    '/images/destinations/lasVegas.png',
    'Los Angeles travel destination',
    'Call to book',
    'Why visit Los Angeles?',
    'From coast to canyons, LA offers entertainment, outdoor space, and diverse neighborhoods.',
    'Best time to visit',
    'March–May and September–November usually bring comfortable temperatures and clearer skies.',
    'Flights to Los Angeles | FlightBugs',
    'Book flights to Los Angeles by phone. Search live fares, then call FlightBugs 24/7.',
    'flights to Los Angeles'
  ),
  (
    'Honolulu',
    'honolulu',
    'Hawaii',
    'United States',
    'Pacific beaches and island culture.',
    'Honolulu is the gateway to Oahu. Search fares, then call our desk to ticket by phone.',
    TRUE,
    FALSE,
    TRUE,
    6,
    'Honolulu',
    'Island gateway',
    'Search live fares to Honolulu, then call a specialist to ticket by phone.',
    '/images/destinations/cancun.png',
    'Honolulu Hawaii travel destination',
    'Call to book',
    'Why visit Honolulu?',
    'Beaches, reefs, and Hawaiian culture make Honolulu a standout Pacific getaway.',
    'Best time to visit',
    'April–June and September–early December often balance weather and fewer crowds.',
    'Flights to Honolulu | FlightBugs',
    'Book flights to Honolulu by phone. Search live fares, then call FlightBugs 24/7.',
    'flights to Honolulu'
  ),
  (
    'Denver',
    'denver',
    'Colorado',
    'United States',
    'Mile-high city and Rocky Mountain access.',
    'Denver pairs urban energy with mountain trips. Search, then ticket by phone with our desk.',
    TRUE,
    FALSE,
    TRUE,
    7,
    'Denver',
    'Gateway to the Rockies',
    'Search live fares to Denver, then call a specialist to ticket by phone.',
    '/images/destinations/montreal.png',
    'Denver Colorado travel destination',
    'Call to book',
    'Why visit Denver?',
    'Breweries, culture, and easy mountain day trips make Denver a strong base for Colorado travel.',
    'Best time to visit',
    'Late spring through early fall is ideal for outdoor plans; winter suits ski-trip connections.',
    'Flights to Denver | FlightBugs',
    'Book flights to Denver by phone. Search live fares, then call FlightBugs 24/7.',
    'flights to Denver'
  ),
  (
    'Chicago',
    'chicago',
    'Illinois',
    'United States',
    'Architecture, lakefront, and deep-dish classics.',
    'Chicago delivers museums, parks, and neighborhoods. Search fares, then call to ticket by phone.',
    TRUE,
    FALSE,
    TRUE,
    8,
    'Chicago',
    'Windy City',
    'Search live fares to Chicago, then call a specialist to ticket by phone.',
    '/images/destinations/newYork.png',
    'Chicago skyline travel destination',
    'Call to book',
    'Why visit Chicago?',
    'Lakefront parks, architecture, and food culture make Chicago a year-round city break.',
    'Best time to visit',
    'May–October is most comfortable outdoors; winter is colder but rich with indoor culture.',
    'Flights to Chicago | FlightBugs',
    'Book flights to Chicago by phone. Search live fares, then call FlightBugs 24/7.',
    'flights to Chicago'
  )
ON CONFLICT (slug) DO NOTHING;

INSERT INTO destination_faqs (destination_id, question, answer, sort_order)
SELECT d.id, q.question, q.answer, q.sort_order
FROM destinations d
CROSS JOIN (
  VALUES
    (1, 'How do I book flights to this destination?', 'Search live fares on FlightBugs, then call our desk. A specialist confirms the live fare and tickets by phone.'),
    (2, 'When can I call?', 'Our desk is available 24/7 for travelers in Canada and the USA.')
) AS q(sort_order, question, answer)
WHERE d.slug IN (
  'new-york',
  'orlando',
  'las-vegas',
  'miami',
  'los-angeles',
  'honolulu',
  'denver',
  'chicago'
)
AND NOT EXISTS (
  SELECT 1 FROM destination_faqs f WHERE f.destination_id = d.id
);
